#ifndef HEADER_H
#define HEADER_H

const char index_html[] =
"<!DOCTYPE html>\r\n"
"<html lang=\"en\">\r\n"
"<head>\r\n"
"    <meta charset=\"UTF-8\">\r\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
"    <style>\r\n"
"        /* \xD0\x9E\xD1\x81\xD0\xBD\xD0\xBE\xD0\xB2\xD0\xBD\xD1\x8B\xD0\xB5 \xD0\xBD\xD0\xB0\xD1\x81\xD1\x82\xD1\x80\xD0\xBE\xD0\xB9\xD0\xBA\xD0\xB8 \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xB2\xD1\x81\xD0\xB5\xD0\xB3\xD0\xBE \xD1\x82\xD0\xB5\xD0\xBB\xD0\xB0 \xD1\x81\xD1\x82\xD1\x80\xD0\xB0\xD0\xBD\xD0\xB8\xD1\x86\xD1\x8B */\r\n"
"        body {\r\n"
"            margin: 0;\r\n"
"            padding: 0;\r\n"
"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n"
"            background: url('background.jpg') no-repeat center center fixed;\r\n"
"            background-size: cover;\r\n"
"            color: #ffffff;\r\n"
"        }\r\n"
"\r\n"
"        /* \xD0\xA6\xD0\xB5\xD0\xBD\xD1\x82\xD1\x80\xD0\xBE\xD0\xB2\xD0\xBA\xD0\xB0 \xD0\xB2\xD1\x81\xD0\xB5\xD0\xB3\xD0\xBE \xD1\x81\xD0\xBE\xD0\xB4\xD0\xB5\xD1\x80\xD0\xB6\xD0\xB8\xD0\xBC\xD0\xBE\xD0\xB3\xD0\xBE \xD0\xBF\xD0\xBE \xD0\xB2\xD0\xB5\xD1\x80\xD1\x82\xD0\xB8\xD0\xBA\xD0\xB0\xD0\xBB\xD0\xB8 \xD0\xB8 \xD0\xB3\xD0\xBE\xD1\x80\xD0\xB8\xD0\xB7\xD0\xBE\xD0\xBD\xD1\x82\xD0\xB0\xD0\xBB\xD0\xB8 */\r\n"
"        body, html {\r\n"
"            height: 100%;\r\n"
"            display: flex;\r\n"
"            flex-direction: column;\r\n"
"            align-items: center;\r\n"
"            justify-content: flex-start;\r\n"
"            padding: 2rem;\r\n"
"            box-sizing: border-box;\r\n"
"        }\r\n"
"\r\n"
"        /* \xD0\xA1\xD1\x82\xD0\xB8\xD0\xBB\xD0\xB8 \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xB7\xD0\xB0\xD0\xB3\xD0\xBE\xD0\xBB\xD0\xBE\xD0\xB2\xD0\xBA\xD0\xBE\xD0\xB2 h2 \xD0\xB8 h3 */\r\n"
"        h2, h3 {\r\n"
"            text-align: center;\r\n"
"            margin-bottom: 1rem;\r\n"
"            text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.5);\r\n"
"        }\r\n"
"\r\n"
"        /* \xD0\x9E\xD0\xB1\xD1\x89\xD0\xB8\xD0\xB9 \xD1\x81\xD1\x82\xD0\xB8\xD0\xBB\xD1\x8C \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xB2\xD1\x81\xD0\xB5\xD1\x85 \xD1\x84\xD0\xBE\xD1\x80\xD0\xBC */\r\n"
"        form, #randKeysBlock {\r\n"
"            background-color: rgba(0, 0, 0, 0.6);\r\n"
"            padding: 2rem;\r\n"
"            border-radius: 10px;\r\n"
"            margin: 1rem 0;\r\n"
"            width: 100%;\r\n"
"            max-width: 500px;\r\n"
"            box-shadow: 0 0 10px rgba(255, 255, 255, 0.2);\r\n"
"        }\r\n"
"\r\n"
"        /* \xD0\x9E\xD0\xB1\xD1\x89\xD0\xB8\xD0\xB9 \xD1\x81\xD1\x82\xD0\xB8\xD0\xBB\xD1\x8C \xD0\xB4\xD0\xBB\xD1\x8F \xD1\x8D\xD0\xBB\xD0\xB5\xD0\xBC\xD0\xB5\xD0\xBD\xD1\x82\xD0\xBE\xD0\xB2 \xD1\x84\xD0\xBE\xD1\x80\xD0\xBC\xD1\x8B */\r\n"
"        label, input, select, button, p {\r\n"
"            display: block;\r\n"
"            width: 100%;\r\n"
"            margin-bottom: 1rem;\r\n"
"            font-size: 1rem;\r\n"
"        }\r\n"
"\r\n"
"        /* \xD0\xA1\xD1\x82\xD0\xB8\xD0\xBB\xD0\xB8 \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xBF\xD0\xBE\xD0\xBB\xD0\xB5\xD0\xB9 \xD0\xB2\xD0\xB2\xD0\xBE\xD0\xB4\xD0\xB0 \xD0\xB8 \xD0\xB2\xD1\x8B\xD0\xBF\xD0\xB0\xD0\xB4\xD0\xB0\xD1\x8E\xD1\x89\xD0\xB8\xD1\x85 \xD1\x81\xD0\xBF\xD0\xB8\xD1\x81\xD0\xBA\xD0\xBE\xD0\xB2 */\r\n"
"        input, select {\r\n"
"            padding: 0.5rem;\r\n"
"            border: none;\r\n"
"            border-radius: 5px;\r\n"
"        }\r\n"
"\r\n"
"            /* \xD0\x9A\xD0\xBD\xD0\xBE\xD0\xBF\xD0\xBA\xD0\xB8: \xD0\xBE\xD1\x82\xD0\xBF\xD1\x80\xD0\xB0\xD0\xB2\xD0\xBA\xD0\xB0 \xD1\x84\xD0\xBE\xD1\x80\xD0\xBC\xD1\x8B \xD0\xB8 \xD0\xBE\xD0\xB1\xD1\x8B\xD1\x87\xD0\xBD\xD1\x8B\xD0\xB5 */\r\n"
"            input[type=\"submit\"], button {\r\n"
"                background-color: #3498db;\r\n"
"                color: white;\r\n"
"                cursor: pointer;\r\n"
"                transition: background 0.3s ease;\r\n"
"            }\r\n"
"\r\n"
"                /* \xD0\xAD\xD1\x84\xD1\x84\xD0\xB5\xD0\xBA\xD1\x82 \xD0\xBF\xD1\x80\xD0\xB8 \xD0\xBD\xD0\xB0\xD0\xB2\xD0\xB5\xD0\xB4\xD0\xB5\xD0\xBD\xD0\xB8\xD0\xB8 \xD0\xBD\xD0\xB0 \xD0\xBA\xD0\xBD\xD0\xBE\xD0\xBF\xD0\xBA\xD1\x83 */\r\n"
"                input[type=\"submit\"]:hover, button:hover {\r\n"
"                    background-color: #2980b9;\r\n"
"                }\r\n"
"\r\n"
"        /* \xD0\xA1\xD1\x82\xD0\xB8\xD0\xBB\xD1\x8C \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xBF\xD0\xBE\xD0\xBB\xD1\x8F \xD1\x81 RSA \xD0\xBA\xD0\xBB\xD1\x8E\xD1\x87\xD0\xB0\xD0\xBC\xD0\xB8 */\r\n"
"        #randKeysLabel {\r\n"
"            word-wrap: break-word;\r\n"
"            white-space: pre-wrap;\r\n"
"            background-color: rgba(255, 255, 255, 0.1);\r\n"
"            padding: 1rem;\r\n"
"            border-radius: 5px;\r\n"
"        }\r\n"
"\r\n"
"        /* \xD0\x96\xD0\xB8\xD1\x80\xD0\xBD\xD1\x8B\xD0\xB9 \xD1\x88\xD1\x80\xD0\xB8\xD1\x84\xD1\x82 \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xBF\xD0\xBE\xD0\xBB\xD1\x8F \xD0\xB8\xD1\x81\xD0\xBF\xD0\xBE\xD0\xBB\xD1\x8C\xD0\xB7\xD0\xBE\xD0\xB2\xD0\xB0\xD0\xBD\xD0\xB8\xD1\x8F \xD0\xBF\xD0\xB0\xD0\xBC\xD1\x8F\xD1\x82\xD0\xB8 */\r\n"
"        #cmemuse {\r\n"
"            font-weight: bold;\r\n"
"        }\r\n"
"\r\n"
"    </style>\r\n"
"    <title>SEcrypt</title>\r\n"
"    <script>\r\n"
"        function updateCounter() {\r\n"
"            fetch('/getmemuse')\r\n"
"                .then(response => response.text())\r\n"
"                .then(data => {\r\n"
"                    document.getElementById('cmemuse').innerText = data;\r\n"
"                });\r\n"
"        }\r\n"
"        setInterval(updateCounter, 200);\r\n"
"        async function genRandRSA() {\r\n"
"            const gendLabel = document.getElementById('randKeysLabel');\r\n"
"            const n_bits = document.getElementById('n_bits').value;\r\n"
"\r\n"
"            gendLabel.textContent = 'Generating...';\r\n"
"            try {\r\n"
"                const formData = new FormData();\r\n"
"                formData.append('n_bits', n_bits);\r\n"
"                const response = await fetch('/generate_rsa_key', {\r\n"
"                    method: 'POST',\r\n"
"                    body: formData\r\n"
"                });\r\n"
"                const data = await response.json();\r\n"
"                gendLabel.textContent = `Private key: ${data.private_key} Public key: ${data.public_key}`;\r\n"
"            } catch (error) {\r\n"
"                gendLabel.textContent = `Error: ${error.message}`;\r\n"
"            }\r\n"
"        }\r\n"
"    </script>\r\n"
"</head>\r\n"
"<body>\r\n"
"    <h2 style=\"color:black\">Encrypt</h2>\r\n"
"    <form action=\"/process\" method=\"POST\" enctype=\"multipart/form-data\">\r\n"
"        <label for=\"file\">Choose a file with plaintext/ciphertext:</label><br>\r\n"
"        <input type=\"file\" id=\"file\" name=\"file\" required><br><br>\r\n"
"        <label for=\"key\">Enter password:</label><br>\r\n"
"        <input type=\"text\" id=\"password\" name=\"password\"><br><br>\r\n"
"        <label for=\"key\">RSA private key (decrypt) or public key (encrypt):</label><br>\r\n"
"        <input type=\"text\" id=\"rsa_key\" name=\"rsa_key\"><br><br>\r\n"
"        <label for=\"algorithm\">Choose an algorithm:</label><br>\r\n"
"        <select id=\"algorithm\" name=\"algorithm\">\r\n"
"            <option value=\"aes256\">AES256</option>\r\n"
"            <option value=\"rsa\">RSA</option>\r\n"
"        </select><br><br>\r\n"
"        <select id=\"action\" name=\"action\">\r\n"
"            <option value=\"encrypt\">Encrypt</option>\r\n"
"            <option value=\"decrypt\">Decrypt</option>\r\n"
"        </select><br><br>\r\n"
"\r\n"
"        <input type=\"submit\" value=\"Encrypt\">\r\n"
"    </form>\r\n"
"    <div id=\"randKeysBlock\">\r\n"
"        <input type=\"number\" id=\"n_bits\" value=256 />\r\n"
"        <button onclick=\"genRandRSA()\">Random</button>\r\n"
"        <p id=\"randKeysLabel\"></p>\r\n"
"    </div>\r\n"
"    <form action=\"/process_steg\" method=\"POST\" enctype=\"multipart/form-data\">\r\n"
"        <label for=\"file\">Choose a file to hide or a file to reveal the data from:</label><br>\r\n"
"        <input type=\"file\" id=\"file\" name=\"file\" required><br><br>\r\n"
"        <label for=\"cover_file\">Choose a cover file:</label><br>\r\n"
"        <input type=\"file\" id=\"cover_file\" name=\"cover_file\" required><br><br>\r\n"
"        <select id=\"algorithm\" name=\"algorithm\">\r\n"
"            <option value=\"text\">Text</option>\r\n"
"            <option value=\"wav\">WAV</option>\r\n"
"        </select><br><br>\r\n"
"        <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter password (only for wav mode)\"><br><br>\r\n"
"        <select id=\"action\" name=\"action\">\r\n"
"            <option value=\"hide\">Hide</option>\r\n"
"            <option value=\"reveal\">Reveal</option>\r\n"
"        </select><br><br>\r\n"
"\r\n"
"        <input type=\"submit\" value=\"Hide\">\r\n"
"    </form>\r\n"
"<!--    <form action=\"/process_wav\" method=\"POST\" enctype=\"multipart/form-data\">\r\n"
"        <label for=\"wav_file\">Choose a WAV file:</label><br>\r\n"
"        <input type=\"file\" id=\"wav_file\" name=\"wav_file\" required><br><br>\r\n"
"        <label for=\"text\">Enter text to hide or choose a file to hide:</label><br>\r\n"
"        <input type=\"text\" id=\"text\" name=\"text\"><br><br>\r\n"
"        <input type=\"file\" id=\"file_to_hide\" name=\"file_to_hide\"><br><br>\r\n"
"        <input type=\"submit\" value=\"Hide in WAV\">\r\n"
"    </form>-->\r\n"
"\r\n"
"    <h3>Memory usage: <span id=\"cmemuse\">0</span></h3>\r\n"
"</body>\r\n"
"</html>\r\n"
"";

#endif // HEADER_H
