#ifndef HEADER_H
#define HEADER_H

const char index_html[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <style>\n"
"        /* \xD0\x9E\xD1\x81\xD0\xBD\xD0\xBE\xD0\xB2\xD0\xBD\xD1\x8B\xD0\xB5 \xD0\xBD\xD0\xB0\xD1\x81\xD1\x82\xD1\x80\xD0\xBE\xD0\xB9\xD0\xBA\xD0\xB8 \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xB2\xD1\x81\xD0\xB5\xD0\xB3\xD0\xBE \xD1\x82\xD0\xB5\xD0\xBB\xD0\xB0 \xD1\x81\xD1\x82\xD1\x80\xD0\xB0\xD0\xBD\xD0\xB8\xD1\x86\xD1\x8B */\n"
"        body {\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
"            background: url('background.jpg') no-repeat center center fixed;\n"
"            background-size: cover;\n"
"            color: #ffffff;\n"
"        }\n"
"\n"
"        /* \xD0\xA6\xD0\xB5\xD0\xBD\xD1\x82\xD1\x80\xD0\xBE\xD0\xB2\xD0\xBA\xD0\xB0 \xD0\xB2\xD1\x81\xD0\xB5\xD0\xB3\xD0\xBE \xD1\x81\xD0\xBE\xD0\xB4\xD0\xB5\xD1\x80\xD0\xB6\xD0\xB8\xD0\xBC\xD0\xBE\xD0\xB3\xD0\xBE \xD0\xBF\xD0\xBE \xD0\xB2\xD0\xB5\xD1\x80\xD1\x82\xD0\xB8\xD0\xBA\xD0\xB0\xD0\xBB\xD0\xB8 \xD0\xB8 \xD0\xB3\xD0\xBE\xD1\x80\xD0\xB8\xD0\xB7\xD0\xBE\xD0\xBD\xD1\x82\xD0\xB0\xD0\xBB\xD0\xB8 */\n"
"        body, html {\n"
"            height: 100%;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            align-items: center;\n"
"            justify-content: flex-start;\n"
"            padding: 2rem;\n"
"            box-sizing: border-box;\n"
"        }\n"
"\n"
"        /* \xD0\xA1\xD1\x82\xD0\xB8\xD0\xBB\xD0\xB8 \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xB7\xD0\xB0\xD0\xB3\xD0\xBE\xD0\xBB\xD0\xBE\xD0\xB2\xD0\xBA\xD0\xBE\xD0\xB2 h2 \xD0\xB8 h3 */\n"
"        h2, h3 {\n"
"            text-align: center;\n"
"            margin-bottom: 1rem;\n"
"            text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.5);\n"
"        }\n"
"\n"
"        /* \xD0\x9E\xD0\xB1\xD1\x89\xD0\xB8\xD0\xB9 \xD1\x81\xD1\x82\xD0\xB8\xD0\xBB\xD1\x8C \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xB2\xD1\x81\xD0\xB5\xD1\x85 \xD1\x84\xD0\xBE\xD1\x80\xD0\xBC */\n"
"        form, #randKeysBlock {\n"
"            background-color: rgba(0, 0, 0, 0.6);\n"
"            padding: 2rem;\n"
"            border-radius: 10px;\n"
"            margin: 1rem 0;\n"
"            width: 100%;\n"
"            max-width: 500px;\n"
"            box-shadow: 0 0 10px rgba(255, 255, 255, 0.2);\n"
"        }\n"
"\n"
"        /* \xD0\x9E\xD0\xB1\xD1\x89\xD0\xB8\xD0\xB9 \xD1\x81\xD1\x82\xD0\xB8\xD0\xBB\xD1\x8C \xD0\xB4\xD0\xBB\xD1\x8F \xD1\x8D\xD0\xBB\xD0\xB5\xD0\xBC\xD0\xB5\xD0\xBD\xD1\x82\xD0\xBE\xD0\xB2 \xD1\x84\xD0\xBE\xD1\x80\xD0\xBC\xD1\x8B */\n"
"        label, input, select, button, p {\n"
"            display: block;\n"
"            width: 100%;\n"
"            margin-bottom: 1rem;\n"
"            font-size: 1rem;\n"
"        }\n"
"\n"
"        /* \xD0\xA1\xD1\x82\xD0\xB8\xD0\xBB\xD0\xB8 \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xBF\xD0\xBE\xD0\xBB\xD0\xB5\xD0\xB9 \xD0\xB2\xD0\xB2\xD0\xBE\xD0\xB4\xD0\xB0 \xD0\xB8 \xD0\xB2\xD1\x8B\xD0\xBF\xD0\xB0\xD0\xB4\xD0\xB0\xD1\x8E\xD1\x89\xD0\xB8\xD1\x85 \xD1\x81\xD0\xBF\xD0\xB8\xD1\x81\xD0\xBA\xD0\xBE\xD0\xB2 */\n"
"        input, select {\n"
"            padding: 0.5rem;\n"
"            border: none;\n"
"            border-radius: 5px;\n"
"        }\n"
"\n"
"            /* \xD0\x9A\xD0\xBD\xD0\xBE\xD0\xBF\xD0\xBA\xD0\xB8: \xD0\xBE\xD1\x82\xD0\xBF\xD1\x80\xD0\xB0\xD0\xB2\xD0\xBA\xD0\xB0 \xD1\x84\xD0\xBE\xD1\x80\xD0\xBC\xD1\x8B \xD0\xB8 \xD0\xBE\xD0\xB1\xD1\x8B\xD1\x87\xD0\xBD\xD1\x8B\xD0\xB5 */\n"
"            input[type=\"submit\"], button {\n"
"                background-color: #3498db;\n"
"                color: white;\n"
"                cursor: pointer;\n"
"                transition: background 0.3s ease;\n"
"            }\n"
"\n"
"                /* \xD0\xAD\xD1\x84\xD1\x84\xD0\xB5\xD0\xBA\xD1\x82 \xD0\xBF\xD1\x80\xD0\xB8 \xD0\xBD\xD0\xB0\xD0\xB2\xD0\xB5\xD0\xB4\xD0\xB5\xD0\xBD\xD0\xB8\xD0\xB8 \xD0\xBD\xD0\xB0 \xD0\xBA\xD0\xBD\xD0\xBE\xD0\xBF\xD0\xBA\xD1\x83 */\n"
"                input[type=\"submit\"]:hover, button:hover {\n"
"                    background-color: #2980b9;\n"
"                }\n"
"\n"
"        /* \xD0\xA1\xD1\x82\xD0\xB8\xD0\xBB\xD1\x8C \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xBF\xD0\xBE\xD0\xBB\xD1\x8F \xD1\x81 RSA \xD0\xBA\xD0\xBB\xD1\x8E\xD1\x87\xD0\xB0\xD0\xBC\xD0\xB8 */\n"
"        #randKeysLabel {\n"
"            word-wrap: break-word;\n"
"            white-space: pre-wrap;\n"
"            background-color: rgba(255, 255, 255, 0.1);\n"
"            padding: 1rem;\n"
"            border-radius: 5px;\n"
"        }\n"
"\n"
"        /* \xD0\x96\xD0\xB8\xD1\x80\xD0\xBD\xD1\x8B\xD0\xB9 \xD1\x88\xD1\x80\xD0\xB8\xD1\x84\xD1\x82 \xD0\xB4\xD0\xBB\xD1\x8F \xD0\xBF\xD0\xBE\xD0\xBB\xD1\x8F \xD0\xB8\xD1\x81\xD0\xBF\xD0\xBE\xD0\xBB\xD1\x8C\xD0\xB7\xD0\xBE\xD0\xB2\xD0\xB0\xD0\xBD\xD0\xB8\xD1\x8F \xD0\xBF\xD0\xB0\xD0\xBC\xD1\x8F\xD1\x82\xD0\xB8 */\n"
"        #cmemuse {\n"
"            font-weight: bold;\n"
"        }\n"
"\n"
"    </style>\n"
"    <title>SEcrypt</title>\n"
"    <script>\n"
"        function updateCounter() {\n"
"            fetch('/getmemuse')\n"
"                .then(response => response.text())\n"
"                .then(data => {\n"
"                    document.getElementById('cmemuse').innerText = data;\n"
"                });\n"
"        }\n"
"        setInterval(updateCounter, 200);\n"
"        async function genRandRSA() {\n"
"            const gendLabel = document.getElementById('randKeysLabel');\n"
"            const n_bits = document.getElementById('n_bits').value;\n"
"\n"
"            gendLabel.textContent = 'Generating...';\n"
"            try {\n"
"                const formData = new FormData();\n"
"                formData.append('n_bits', n_bits);\n"
"                const response = await fetch('/generate_rsa_key', {\n"
"                    method: 'POST',\n"
"                    body: formData\n"
"                });\n"
"                const data = await response.json();\n"
"                gendLabel.textContent = `Private key: ${data.private_key} Public key: ${data.public_key}`;\n"
"            } catch (error) {\n"
"                gendLabel.textContent = `Error: ${error.message}`;\n"
"            }\n"
"        }\n"
"    </script>\n"
"</head>\n"
"<body>\n"
"    <h2 style=\"color:black\">Encrypt</h2>\n"
"    <form action=\"/process\" method=\"POST\" enctype=\"multipart/form-data\">\n"
"        <label for=\"file\">Choose a file with plaintext/ciphertext:</label><br>\n"
"        <input type=\"file\" id=\"file\" name=\"file\" required><br><br>\n"
"        <label for=\"key\">Enter password:</label><br>\n"
"        <input type=\"text\" id=\"password\" name=\"password\"><br><br>\n"
"        <label for=\"key\">RSA private key (decrypt) or public key (encrypt):</label><br>\n"
"        <input type=\"text\" id=\"rsa_key\" name=\"rsa_key\"><br><br>\n"
"        <label for=\"algorithm\">Choose an algorithm:</label><br>\n"
"        <select id=\"algorithm\" name=\"algorithm\">\n"
"            <option value=\"aes256\">AES256</option>\n"
"            <option value=\"rsa\">RSA</option>\n"
"        </select><br><br>\n"
"        <select id=\"action\" name=\"action\">\n"
"            <option value=\"encrypt\">Encrypt</option>\n"
"            <option value=\"decrypt\">Decrypt</option>\n"
"        </select><br><br>\n"
"\n"
"        <input type=\"submit\" value=\"Encrypt\">\n"
"    </form>\n"
"    <div id=\"randKeysBlock\">\n"
"        <input type=\"number\" id=\"n_bits\" value=256 />\n"
"        <button onclick=\"genRandRSA()\">Random</button>\n"
"        <p id=\"randKeysLabel\"></p>\n"
"    </div>\n"
"    <form action=\"/process_steg\" method=\"POST\" enctype=\"multipart/form-data\">\n"
"        <label for=\"file\">Choose a file to hide or a file to reveal the data from:</label><br>\n"
"        <input type=\"file\" id=\"file\" name=\"file\" required><br><br>\n"
"        <label for=\"cover_file\">Choose a cover file:</label><br>\n"
"        <input type=\"file\" id=\"cover_file\" name=\"cover_file\" required><br><br>\n"
"        <select id=\"algorithm\" name=\"algorithm\">\n"
"            <option value=\"text\">Text</option>\n"
"        </select><br><br>\n"
"        <select id=\"action\" name=\"action\">\n"
"            <option value=\"hide\">Hide</option>\n"
"            <option value=\"reveal\">Reveal</option>\n"
"        </select><br><br>\n"
"\n"
"        <input type=\"submit\" value=\"Hide\">\n"
"    </form>\n"
"    <h3>Memory usage: <span id=\"cmemuse\">0</span></h3>\n"
"</body>\n"
"</html>\n"
"";

#endif // HEADER_H
